name: Update JS

on:
  workflow_dispatch:
    inputs:
      branch_type:
        description: 'The branch type to run action on'
        required: true
        default: 'schedule'
        type: choice
        options:
          - 'schedule'
          - 'prev-major-curr-minor'
          - 'curr-major-curr-minor'
          - 'curr-major-next-minor'
  # At 11:55 AM UTC, on day 1 of the month, only in February and August
  schedule:
    - cron: '55 11 1 2,8 *'

permissions: {}

jobs:
  update-js:
    name: Update JS
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: Update JS
        uses: silverstripe/gha-update-js@v1
        with:
          branch_type: ${{ github.event_name == 'schedule' && 'schedule' || github.event.inputs.branch_type }}
